<script>
    document.addEventListener('alpine:init', () => {
        Alpine.data('LumaTabs', () => ({
            init() {
                const tabAnchors = [...this.$el.querySelectorAll('a[data-toggle="trigger"]')];
                tabAnchors.forEach(anchor => {
                    anchor.addEventListener('click', (e) => {
                        e.preventDefault();
                        tabAnchors.forEach(anchor => {
                            anchor.parentNode.classList.remove('active');
                        })

                        const href = e.target.getAttribute('href').replace(/#/g, '');
                        const target = document.getElementById(href);
                        console.log('target href', href);
                        href.parentNode.classList.add('active');
                        target.style.display = 'block';
                    })
                });
            }
        }));
    });
</script>
